mysql:
  write:
    host: 127.0.0.1
    user: root
    password: ""
    port: "3306"
    prefix: "ysb"
  read:
    host: 127.0.0.1
    user: root
    password: ""
    port: "3306"
    prefix: "ysb"
redis:
  host: 127.0.0.1
  port: 6379
  password: ""
mongoDB: false
urls:
  outside:
    - www.baidu.com
    - www.taobao.com
    - www.ysbjob.com
  inside:
    - www.tmall.com
    - 1
    - true
    - 28.9271
    - www.jd.com
test:
  1: a
  2: b
  3: c
money: 15.98